from dataclasses import dataclass

from elaborations.models.dtos.configuration_command_dto import (
    CommandCode,
    CommandType,
)
from elaborations.services.operations.command_scope import (
    SCOPE_HOOK_AFTER_ALL,
    SCOPE_HOOK_AFTER_EACH,
    SCOPE_HOOK_BEFORE_ALL,
    SCOPE_HOOK_BEFORE_EACH,
    SCOPE_MOCK_POST_RESPONSE,
    SCOPE_MOCK_PRE_RESPONSE,
    SCOPE_TEST,
)


@dataclass(frozen=True)
class OperationContract:
    family: str
    name: str
    supported_scopes: tuple[str, ...]
    reads_from: tuple[str, ...]
    writes_to: tuple[str, ...]
    produces_result: bool
    side_effects: bool
    async_allowed: bool
    failure_mode: str


_HOOK_SCOPES = (
    SCOPE_HOOK_BEFORE_ALL,
    SCOPE_HOOK_BEFORE_EACH,
    SCOPE_HOOK_AFTER_EACH,
    SCOPE_HOOK_AFTER_ALL,
)
_HOOK_AND_TEST_SCOPES = (SCOPE_TEST, *_HOOK_SCOPES)

_CONTRACTS: dict[str, OperationContract] = {
    CommandCode.SET_VARIABLE.value: OperationContract(
        family=CommandType.CONTEXT.value,
        name=CommandCode.SET_VARIABLE.value,
        supported_scopes=(SCOPE_TEST, *_HOOK_SCOPES, SCOPE_MOCK_PRE_RESPONSE),
        reads_from=("runEnvelope", "global", "local"),
        writes_to=("runEnvelope", "global", "local", "result"),
        produces_result=True,
        side_effects=False,
        async_allowed=False,
        failure_mode="fail-fast",
    ),
    CommandCode.DELETE_VARIABLE.value: OperationContract(
        family=CommandType.CONTEXT.value,
        name=CommandCode.DELETE_VARIABLE.value,
        supported_scopes=_HOOK_AND_TEST_SCOPES,
        reads_from=("runEnvelope", "global", "local"),
        writes_to=("global", "local", "result"),
        produces_result=True,
        side_effects=False,
        async_allowed=False,
        failure_mode="fail-fast",
    ),
    CommandCode.SLEEP.value: OperationContract(
        family=CommandType.ACTION.value,
        name=CommandCode.SLEEP.value,
        supported_scopes=_HOOK_AND_TEST_SCOPES,
        reads_from=("local",),
        writes_to=("result",),
        produces_result=True,
        side_effects=False,
        async_allowed=False,
        failure_mode="fail-fast",
    ),
    CommandCode.READ_API.value: OperationContract(
        family=CommandType.ACTION.value,
        name=CommandCode.READ_API.value,
        supported_scopes=(SCOPE_TEST, *_HOOK_SCOPES, SCOPE_MOCK_POST_RESPONSE),
        reads_from=("runEnvelope", "global", "local"),
        writes_to=("result",),
        produces_result=True,
        side_effects=True,
        async_allowed=True,
        failure_mode="fail-fast",
    ),
    CommandCode.WRITE_API.value: OperationContract(
        family=CommandType.ACTION.value,
        name=CommandCode.WRITE_API.value,
        supported_scopes=(SCOPE_TEST, *_HOOK_SCOPES, SCOPE_MOCK_POST_RESPONSE),
        reads_from=("runEnvelope", "global", "local"),
        writes_to=("result",),
        produces_result=True,
        side_effects=True,
        async_allowed=True,
        failure_mode="fail-fast",
    ),
    CommandCode.SEND_MESSAGE_QUEUE.value: OperationContract(
        family=CommandType.ACTION.value,
        name=CommandCode.SEND_MESSAGE_QUEUE.value,
        supported_scopes=(SCOPE_TEST, *_HOOK_SCOPES, SCOPE_MOCK_POST_RESPONSE),
        reads_from=("runEnvelope", "global", "local"),
        writes_to=("result",),
        produces_result=True,
        side_effects=True,
        async_allowed=True,
        failure_mode="fail-fast",
    ),
    CommandCode.SAVE_TABLE.value: OperationContract(
        family=CommandType.ACTION.value,
        name=CommandCode.SAVE_TABLE.value,
        supported_scopes=(SCOPE_TEST, *_HOOK_SCOPES, SCOPE_MOCK_POST_RESPONSE),
        reads_from=("runEnvelope", "global", "local"),
        writes_to=("result",),
        produces_result=True,
        side_effects=True,
        async_allowed=True,
        failure_mode="fail-fast",
    ),
    CommandCode.DROP_TABLE.value: OperationContract(
        family=CommandType.ACTION.value,
        name=CommandCode.DROP_TABLE.value,
        supported_scopes=(SCOPE_TEST, *_HOOK_SCOPES, SCOPE_MOCK_POST_RESPONSE),
        reads_from=(),
        writes_to=("result",),
        produces_result=True,
        side_effects=True,
        async_allowed=True,
        failure_mode="fail-fast",
    ),
    CommandCode.CLEAN_TABLE.value: OperationContract(
        family=CommandType.ACTION.value,
        name=CommandCode.CLEAN_TABLE.value,
        supported_scopes=(SCOPE_TEST, *_HOOK_SCOPES, SCOPE_MOCK_POST_RESPONSE),
        reads_from=(),
        writes_to=("result",),
        produces_result=True,
        side_effects=True,
        async_allowed=True,
        failure_mode="fail-fast",
    ),
    CommandCode.EXPORT_DATASET.value: OperationContract(
        family=CommandType.ACTION.value,
        name=CommandCode.EXPORT_DATASET.value,
        supported_scopes=(SCOPE_TEST, *_HOOK_SCOPES, SCOPE_MOCK_POST_RESPONSE),
        reads_from=("runEnvelope", "global", "local"),
        writes_to=("result",),
        produces_result=True,
        side_effects=True,
        async_allowed=True,
        failure_mode="fail-fast",
    ),
    CommandCode.DROP_DATASET.value: OperationContract(
        family=CommandType.ACTION.value,
        name=CommandCode.DROP_DATASET.value,
        supported_scopes=(SCOPE_TEST, *_HOOK_SCOPES, SCOPE_MOCK_POST_RESPONSE),
        reads_from=(),
        writes_to=("result",),
        produces_result=True,
        side_effects=True,
        async_allowed=True,
        failure_mode="fail-fast",
    ),
    CommandCode.CLEAN_DATASET.value: OperationContract(
        family=CommandType.ACTION.value,
        name=CommandCode.CLEAN_DATASET.value,
        supported_scopes=(SCOPE_TEST, *_HOOK_SCOPES, SCOPE_MOCK_POST_RESPONSE),
        reads_from=(),
        writes_to=("result",),
        produces_result=True,
        side_effects=True,
        async_allowed=True,
        failure_mode="fail-fast",
    ),
    CommandCode.RUN_SUITE.value: OperationContract(
        family=CommandType.ACTION.value,
        name=CommandCode.RUN_SUITE.value,
        supported_scopes=(SCOPE_TEST, *_HOOK_SCOPES, SCOPE_MOCK_POST_RESPONSE),
        reads_from=("runEnvelope", "global", "local"),
        writes_to=("result",),
        produces_result=True,
        side_effects=True,
        async_allowed=True,
        failure_mode="fail-fast",
    ),
    CommandCode.RECEIVE_QUEUE.value: OperationContract(
        family=CommandType.ACTION.value,
        name=CommandCode.RECEIVE_QUEUE.value,
        supported_scopes=(SCOPE_TEST, *_HOOK_SCOPES, SCOPE_MOCK_POST_RESPONSE),
        reads_from=("runEnvelope", "global", "local"),
        writes_to=("runEnvelope", "local", "result"),
        produces_result=True,
        side_effects=False,
        async_allowed=False,
        failure_mode="fail-fast",
    ),
    CommandCode.QUERY_DATABASE.value: OperationContract(
        family=CommandType.ACTION.value,
        name=CommandCode.QUERY_DATABASE.value,
        supported_scopes=(SCOPE_TEST, *_HOOK_SCOPES, SCOPE_MOCK_POST_RESPONSE),
        reads_from=("runEnvelope", "global", "local"),
        writes_to=("runEnvelope", "local", "result"),
        produces_result=True,
        side_effects=False,
        async_allowed=False,
        failure_mode="fail-fast",
    ),
    CommandCode.JSON_EQUALS.value: OperationContract(
        family=CommandType.ASSERT.value,
        name=CommandCode.JSON_EQUALS.value,
        supported_scopes=(SCOPE_TEST, SCOPE_MOCK_PRE_RESPONSE),
        reads_from=("runEnvelope", "global", "local", "result"),
        writes_to=("result",),
        produces_result=True,
        side_effects=False,
        async_allowed=False,
        failure_mode="fail-fast",
    ),
    CommandCode.JSON_EMPTY.value: OperationContract(
        family=CommandType.ASSERT.value,
        name=CommandCode.JSON_EMPTY.value,
        supported_scopes=(SCOPE_TEST, SCOPE_MOCK_PRE_RESPONSE),
        reads_from=("runEnvelope", "global", "local", "result"),
        writes_to=("result",),
        produces_result=True,
        side_effects=False,
        async_allowed=False,
        failure_mode="fail-fast",
    ),
    CommandCode.JSON_NOT_EMPTY.value: OperationContract(
        family=CommandType.ASSERT.value,
        name=CommandCode.JSON_NOT_EMPTY.value,
        supported_scopes=(SCOPE_TEST, SCOPE_MOCK_PRE_RESPONSE),
        reads_from=("runEnvelope", "global", "local", "result"),
        writes_to=("result",),
        produces_result=True,
        side_effects=False,
        async_allowed=False,
        failure_mode="fail-fast",
    ),
    CommandCode.JSON_CONTAINS.value: OperationContract(
        family=CommandType.ASSERT.value,
        name=CommandCode.JSON_CONTAINS.value,
        supported_scopes=(SCOPE_TEST, SCOPE_MOCK_PRE_RESPONSE),
        reads_from=("runEnvelope", "global", "local", "result"),
        writes_to=("result",),
        produces_result=True,
        side_effects=False,
        async_allowed=False,
        failure_mode="fail-fast",
    ),
    CommandCode.JSON_ARRAY_EQUALS.value: OperationContract(
        family=CommandType.ASSERT.value,
        name=CommandCode.JSON_ARRAY_EQUALS.value,
        supported_scopes=(SCOPE_TEST, SCOPE_MOCK_PRE_RESPONSE),
        reads_from=("runEnvelope", "global", "local", "result"),
        writes_to=("result",),
        produces_result=True,
        side_effects=False,
        async_allowed=False,
        failure_mode="fail-fast",
    ),
    CommandCode.JSON_ARRAY_EMPTY.value: OperationContract(
        family=CommandType.ASSERT.value,
        name=CommandCode.JSON_ARRAY_EMPTY.value,
        supported_scopes=(SCOPE_TEST, SCOPE_MOCK_PRE_RESPONSE),
        reads_from=("runEnvelope", "global", "local", "result"),
        writes_to=("result",),
        produces_result=True,
        side_effects=False,
        async_allowed=False,
        failure_mode="fail-fast",
    ),
    CommandCode.JSON_ARRAY_NOT_EMPTY.value: OperationContract(
        family=CommandType.ASSERT.value,
        name=CommandCode.JSON_ARRAY_NOT_EMPTY.value,
        supported_scopes=(SCOPE_TEST, SCOPE_MOCK_PRE_RESPONSE),
        reads_from=("runEnvelope", "global", "local", "result"),
        writes_to=("result",),
        produces_result=True,
        side_effects=False,
        async_allowed=False,
        failure_mode="fail-fast",
    ),
    CommandCode.JSON_ARRAY_CONTAINS.value: OperationContract(
        family=CommandType.ASSERT.value,
        name=CommandCode.JSON_ARRAY_CONTAINS.value,
        supported_scopes=(SCOPE_TEST, SCOPE_MOCK_PRE_RESPONSE),
        reads_from=("runEnvelope", "global", "local", "result"),
        writes_to=("result",),
        produces_result=True,
        side_effects=False,
        async_allowed=False,
        failure_mode="fail-fast",
    ),
}


def get_operation_contract(operation_type: str) -> OperationContract | None:
    normalized = str(operation_type or "").strip()
    return _CONTRACTS.get(normalized)

